### ISSUE TITLE
Polytope installation requires setuptools>=26?

### ISSUE THREAD

**Issue by carterbox** [tulip-control/polytope#29] opened 2016-09-07 21:39 UTC
On a Travis Build for another project using python2.7, the install of polytope failed at `from setuptools import setup`. I updated the version of `setuptools` on the Travis server from 20 to 26. After that, the install succeeded. This probably means there should be a `setuptools>=26` requirement added to `requirements.txt`, but I can't confirm whether this is the most lenient requirement.

**Comment by johnyf** [comment] 2016-09-07 22:05
This is unlikely, because `setuptools == 26.0.0` was released [18 days ago](https://github.com/pypa/setuptools/releases/tag/v26.0.0), and the changes to `setup.py` since then have been mainly docstrings, strings, and whitespace (from 3ff27814e7b3328720f0d760c897e6b3e332d2c0 to 83dfbd35789d0cac92433e3f9b7d14f46244da37).

The only lines executed before `from setuptools import setup` that affect global scope and changed in this period of time are:

```python
from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals
```

which shouldn't relate to `setuptools`. A package failing to import is an installation problem of the package, not a problem with the package that imports it (in this case the script `setup.py`).

The tests [always first upgrade](https://travis-ci.org/tulip-control/polytope/jobs/156727346#L377) both `pip` and `setuptools`, and in releasing `polytope == 0.1.3`, it has thus been tested with `seuptools == 26.1.1`. Running locally in Python 2 a file with the lines up to the failing line does not cause any problems with `setuptools == 20.0.0` nor `setuptools == 26.1.1`.

What is the Travis log of the failure?

**Comment by johnyf** [comment] 2016-09-07 22:19
The error that I see in [`xdesign`](https://travis-ci.org/tomography/xdesign/jobs/158289484#L429) is not at `from setuptools import setup`, but later, when `pip` attempts to build a wheel for `polytope` [within `miniconda`](https://github.com/tomography/xdesign/blob/9d6e00aea74e40abc5846ef9523afbecfad3b60e/.travis.yml#L20), an attempt that results in a cryptic:

```python
TypeError: 'package' must be a string (dot-separated), list, or tuple
```

which, at first, appears totally irrelevant, because `packages` indeed is a `list` that contains one `str`.

It seems that this could be this Python bug:
    https://bugs.python.org/issue13943
which is due to unicode string literals, so it perfectly matches the recent change to `from __future__ import unicode_literals`.
It also appears to be https://github.com/pypa/pip/issues/1441

For reference, [`setuptools == 20.0`](https://github.com/pypa/setuptools/releases/tag/20.0) was released Feb 7 2016.

**Comment by johnyf** [comment] 2016-09-07 22:28
I could reproduce the error locally by running the entire `setup.py` with `setuptools == 22`. The error does not exist with `setuptools == 23`, which goes a few months back.

This type of requirement would likely need to appear in `setup_requires`, so that `pip` can upgrade `setuptools` if needed. Also, upgrading `setuptools` on Travis CI inside `miniconda`, we needed to use `--ignore-installed`.

**Comment by johnyf** [comment] 2016-09-07 22:47
Expected to be addressed by d5c18c20a4d5b5c1f6cf67dedadd1fa6e1fb0131.

**Comment by proyan** [comment] 2017-01-03 14:04
Hi

Even with the current devel version, I get the same error when installing polytope. The traceback is:
`    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-s9hxjC-build/setup.py", line 122, in <module>
        run_setup()
      File "/tmp/pip-s9hxjC-build/setup.py", line 118, in run_setup
        classifiers=classifiers)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 42, in run
        self.build_packages()
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
        self.build_module(module, module_file, package)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 60, in build_module
        outfile, copied = _build_py.build_module(self, module, module_file, package)
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple`

I am trying to install current polytope/devel (d5c18c20a4d5b5c1f6cf67dedadd1fa6e1fb0131) using pip (version 9.1.0.dev0)

**Comment by carterbox** [comment] 2017-01-03 17:07
@proyan This problem is not the same as the one in this issue so in the future. Next time please open a new issue.

In regards to your issue: Is there some reason that you need a development version? Why not use the v0.1.3? Either way, if you need to use v0.1.4, then clone the `tulip-control/master` branch instead of the `tulip-control/dev` branch.

**Comment by proyan** [comment] 2017-01-03 17:28
Thanks for the reply @carterbox 

> Is there some reason that you need a development version. Why not use the v0.1.3? 
I moved to the development version because I was getting this error with the master branch as well. Same for the v0.1.3

> This problem is not the same as the one in this issue so in the future. Next time please open a new issue.
Noted. I was under the impression that this might be a relevant issue, since the latest commit by @johnyf was partly supposed to avoid this error with `setuptools`

Would you have an idea about what is going on here? Is this an issue with pip or polytope?

**Comment by carterbox** [comment] 2017-01-03 17:45
@proyan, can you supply more information about your system setup? e.g. operation system, versions of `pip`, `setuptools`, the explicit commands you are typing into the terminal, etc? Why are you using a dev version of `pip`? Can you try a stable release of `pip`? As I mentioned, I tried to recreate the problem, but I wasn't successful.

**Comment by proyan** [comment] 2017-01-03 18:10
I moved to the pip devel because the current release was giving me this error. Previously I was using 
pip v1.5.4
OS: ubuntu 14.04 64 bit
setuptools 3.3
I am trying to install by: python setup.py install --prefix="/my/install/dir"

**Comment by carterbox** [comment] 2017-01-03 18:58
So to summarize, this is your experience?

SUCCESS:
- download source from github and using `python setup.py install`

FAIL:
- download source from github and using `python setup.py install --prefix="/my/install/dir"`
- `pip install polytope`

**Comment by proyan** [comment] 2017-01-03 19:22
Yes

**Closed** 2017-01-11 08:21 UTC
Labels: bug
